# Export your exact env with:
#   conda env export --from-history > environment.from-history.yml
name: af3-arpeggio
channels: [conda-forge]
dependencies:
  - python=3.11
  - openbabel
  - biopython
  - gemmi
  - numpy
  - pandas
  - matplotlib
  - networkx
  - tk
  - pip
